build_script:
  - ps: .\build.ps1 -Folder $env:folder_filter
test_script:
  - ps: .\test\test.ps1 -Folder $env:folder_filter
environment:
  matrix:
    - folder_filter: 2.1/nanoserver-sac2016/*
    - folder_filter: 2.0/nanoserver-sac2016/*
    - folder_filter: 1.*
matrix:
  fast_finish: true
branches:
  only:
    - master
    - staging
    - dev
    - /^(.*\/)?ci-.*$/
deploy: off
os: Visual Studio 2017
