sudo: required
branches:
  only:
    - master
    - staging
    - dev
    - /^(.*\/)?ci-.*$/
services:
  - docker
env:
  matrix:
    - folder_filter=2.1/*
    - folder_filter=2.0/*
    - folder_filter=1.1/*
    - folder_filter=1.0/*
matrix:
  fast_finish: true
before_install:
  - bash <(curl -fsSL https://raw.githubusercontent.com/PowerShell/PowerShell/v6.0.0-beta.6/tools/download.sh)
script:
  - ./ci-build.sh
